[[redirects]]
  from = "/"
  to = "/main"
  status = 200
  force = true
 
[[redirects]]
  from = "/main"
  to = "/about"
  status = 200
  force = true

 [[redirects]]
  from = "/about"
  to = "/contact"
  status = 200
  force = true